### PR TITLE
Upgrade to Rails 6.1

### PR DESCRIPTION
**Pull request by jackorp**
What works:
`s2i build` for Ruby 2.5...3.0

Running the container (bare in podman without DB && in podman with sqlite DB preinitialized). 

Articles and comments work when using sqlite instead of PG.

What doesn't work: /

What I wasn't tested: That articles work with the Postgresql.

### CODE REVIEW

**Comment by jackorp** [comment]
Works with s2i tests for Fedora: https://gist.github.com/jackorp/cf9c4a3b309493be7a02967ff8be0ab6

**Review by pvalena — APPROVED** [review]
LGTM.

**Comment by pvalena** [comment]
> Articles and comments work when using sqlite instead of PG.
> 
> What I wasn't tested: That articles work with the Postgresql.

@yselkowitz do you think this would be an issue?

**Comment by pvalena** [comment]
@jackorp where is the PostgreSQL / Sqlite setting?

**Comment by jackorp** [comment]
> @jackorp where is the PostgreSQL / Sqlite setting?

should be in `config/database.yml`, I did not touch that as I did not see a reason to.

(For testing I just copied `test:` sqlite config to `production:` and `development`)

**Comment by pvalena** [comment]
> Works with s2i tests for Fedora: https://gist.github.com/jackorp/cf9c4a3b309493be7a02967ff8be0ab6

Can you test with 2.7 / 2.6 / 2.5 as well?

**Comment by jackorp** [comment]
I'll fire the whole test suite now. It's going to take a while.

**Comment by jackorp** [comment]
2.6 and 2.7 pass as well: https://gist.github.com/jackorp/2c3e98fb4750d49b92694304fa14846b

2.5 is not built anymore it seems.

**Comment by jackorp** [comment]
2.6 and 2.7 pass as well: https://gist.github.com/jackorp/2c3e98fb4750d49b92694304fa14846b

**Comment by jackorp** [comment]
JFTR: I did not explicitly test with Postgresql but I do not expect any failure or incompatibility.

Instead, I used SQLite for ease of setup & testing the app itself.

**Comment by pvalena** [comment]
I just noticed this goes into my PR. Let's go with this and figure out the status in the regular PR.

Thanks!

**Pull request merged**
